pipeline:
  build:
    image: node:8-alpine
    commands:
      - npm install
      - npm run test:lint
      - npm run test:js
      - npm run test:ci # generate reports

  publish_gcr:
    image: plugins/gcr
    registry: gcr.io
    repo: rw-k8s/node-starter
    build_args:
     - NPM_TOKEN=${NPM_TOKEN}
    auto_tag: true
    # tags: [latest, '${DRONE_TAG}']
    secrets: [google_credentials]
    when:
      ref: [refs/tags/*, refs/heads/master]
      event: [tag, deployment]

  # helm_deploy_dev:
  #   image: quay.io/ipedrazas/drone-helm:latest
  #   skip_tls_verify: true
  #   chart: ./helm/node-starter
  #   release: node
  #   values: image.tag=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
  #   values_files: ["./helm/node-starter/values.aws.dev.yaml"]
  #   namespace: test
  #   prefix: DEV
  #   secrets: [ dev_api_server, dev_kubernetes_token ]
  #   when:
  #     branch: [develop]
  #     event: [push, tag, deployment]

  slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    channel: iops
    username: drone[Github]
    icon_url: 'https://c1.staticflickr.com/5/4236/34957940160_435d83114f_z.jpg'
    template: >
      Helm Chart: *<https://github.com/{{ repo.owner }}/{{ repo.name }}| {{ repo.name }} >*
      (<https://github.com/{{ repo.owner }}/{{ repo.name }}/commit/{{ build.commit }}|{{ build.branch }}:{{ truncate build.commit 11 }}>)
      release-{{ build.number }} was deployed by {{ build.author }}
      with status: {{ build.status }}. <{{ build.link }} | See details.>
    when:
      status: [ success, failure ]

# branches: [ master, develop, release/*,  ]
