# Default values for node-starter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gcr.io/rw-k8s/node-starter
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: gcr-creds-ro
  extraEnvs:
    - name: PORT
      value: '80'

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    dns.alpha.kubernetes.io/external: "true"
    ingress.kubernetes.io/force-ssl-redirect: "true"
  path: /
  hosts:
    - node.dk.dynamics.net
  tls:
    - secretName: node.dk.dynamics.net
      hosts:
       - node.dk.dynamics.net

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
